set PYTHONPATH=%CD% && python scripts/generate_data.py --form gradient_x --output data/n_accurate_set/bath/x_200_2000.bath --min_value 200 --max_value 2000
set PYTHONPATH=%CD% && python scripts/generate_data.py --form gradient_y --output data/n_accurate_set/bath/y_200_2000.bath --min_value 200 --max_value 2000
set PYTHONPATH=%CD% && python scripts/generate_data.py --form parabola --output data/n_accurate_set/bath/parabola_200_2000.bath --min_value 200 --max_value 2000
set PYTHONPATH=%CD% && python scripts/generate_data.py --form parabola_sine --output data/n_accurate_set/bath/parabola_sine_200_2000.bath --min_value 200 --max_value 2000 --sin_amp 50 --sin_period_x 50 --sin_period_y 70
set PYTHONPATH=%CD% && python scripts/generate_subduction.py --form gaussian --output data/n_accurate_set/waves/gaus_single_2.wave --sigma 50.0 --amplitude 2.0
set PYTHONPATH=%CD% && python scripts/generate_subduction.py --form double_gaussian --output data/n_accurate_set/waves/gaus_double_1_2.wave --sigma 50.0 --amplitude1 1.0 --amplitude2 2.0
set PYTHONPATH=%CD% && python scripts/generate_subduction.py --form double_gaussian --output data/n_accurate_set/waves/gaus_double_2_1.wave --sigma 50.0 --amplitude1 2.0 --amplitude2 1.0
set PYTHONPATH=%CD% && python scripts/generate_basis.py --tile-height 60 --tile-width 80 --output-dir data/n_accurate_set/basises/basis_6 --value 1.0
set PYTHONPATH=%CD% && python scripts/generate_basis.py --tile-height 60 --tile-width 60 --output-dir data/n_accurate_set/basises/basis_8 --value 1.0
set PYTHONPATH=%CD% && python scripts/generate_basis.py --tile-height 40 --tile-width 80 --output-dir data/n_accurate_set/basises/basis_9 --value 1.0
set PYTHONPATH=%CD% && python scripts/generate_basis.py --tile-height 60 --tile-width 48 --output-dir data/n_accurate_set/basises/basis_10 --value 1.0
set PYTHONPATH=%CD% && python scripts/generate_basis.py --tile-height 40 --tile-width 60 --output-dir data/n_accurate_set/basises/basis_12 --value 1.0
set PYTHONPATH=%CD% && python scripts/generate_basis.py --tile-height 40 --tile-width 48 --output-dir data/n_accurate_set/basises/basis_15 --value 1.0
set PYTHONPATH=%CD% && python scripts/generate_basis.py --tile-height 30 --tile-width 60 --output-dir data/n_accurate_set/basises/basis_16 --value 1.0
set PYTHONPATH=%CD% && python scripts/generate_basis.py --tile-height 40 --tile-width 40 --output-dir data/n_accurate_set/basises/basis_18 --value 1.0
set PYTHONPATH=%CD% && python scripts/generate_basis.py --tile-height 30 --tile-width 48 --output-dir data/n_accurate_set/basises/basis_20 --value 1.0
set PYTHONPATH=%CD% && python scripts/generate_basis.py --tile-height 30 --tile-width 40 --output-dir data/n_accurate_set/basises/basis_24 --value 1.0
set PYTHONPATH=%CD% && python scripts/generate_basis.py --tile-height 24 --tile-width 48 --output-dir data/n_accurate_set/basises/basis_25 --value 1.0
set PYTHONPATH=%CD% && python scripts/generate_basis.py --tile-height 24 --tile-width 40 --output-dir data/n_accurate_set/basises/basis_30 --value 1.0
set PYTHONPATH=%CD% && python scripts/generate_basis.py --tile-height 30 --tile-width 30 --output-dir data/n_accurate_set/basises/basis_30 --value 1.0
set PYTHONPATH=%CD% && python scripts/generate_basis.py --tile-height 20 --tile-width 40 --output-dir data/n_accurate_set/basises/basis_36 --value 1.0
set PYTHONPATH=%CD% && python scripts/generate_basis.py --tile-height 24 --tile-width 30 --output-dir data/n_accurate_set/basises/basis_40 --value 1.0
set PYTHONPATH=%CD% && python scripts/generate_basis.py --tile-height 20 --tile-width 30 --output-dir data/n_accurate_set/basises/basis_48 --value 1.0
